package es.us.dad.mysql.entities;

import java.util.Objects;

/**
 * This class represents the values generated by a sensor. Every time the value
 * of a certain sensor is reported, a new instance of this entity will be
 * generated in the database. The values in the database are never overwritten,
 * but new ones are generated with their corresponding timestamp.
 * 
 * @author luismi
 *
 */
public class SensorValue {

	/**
	 * Primary key associated with the sensor value. This identifier is unique for
	 * each value of a sensor in the database. In this way, each time a new sensor
	 * value is generated and it is stored in the database, a new tuple will be
	 * generated with a new identifier.
	 */
	private Integer idSensorValue;

	/**
	 * Numerical value obtained by the sensor associated with the indicated sensor
	 * id.
	 */
	private Float value;

	/**
	 * Identifier of the sensor on which said value has been generated. This sensor
	 * uniquely represents an sensor connected to a device.
	 */
	private Integer idSensor;

	/**
	 * Timestamp in which the data provided by the sensor is generated. The
	 * timestamp is expressed in unix time, defined as the milliseconds since
	 * January 1, 1970.
	 */
	private Long timestamp;

	/**
	 * Logical value indicating if the sensor value has been removed. The
	 * elimination is done by marking this field to true, so the value is never
	 * permanently eliminated from the database.
	 */
	private Boolean removed;
	
	private Integer boxNumber;

	public SensorValue() {
		super();
	}

	public SensorValue(Float value, Integer idSensor, Long timestamp, Boolean removed, Integer boxNumber) {
		super();
		this.value = value;
		this.idSensor = idSensor;
		this.removed = removed;
		this.timestamp = timestamp;
		this.boxNumber = boxNumber;
	}

	public SensorValue(Integer idSensorValue, Float value, Integer idSensor, Long timestamp, Boolean removed, Integer boxNumber) {
		super();
		this.idSensorValue = idSensorValue;
		this.value = value;
		this.idSensor = idSensor;
		this.removed = removed;
		this.timestamp = timestamp;
		this.boxNumber = boxNumber;
	}

	public Float getValue() {
		return value;
	}

	public void setValue(Float value) {
		this.value = value;
	}

	public Integer getIdSensor() {
		return idSensor;
	}

	public void setIdSensor(Integer idSensor) {
		this.idSensor = idSensor;
	}

	public Boolean isRemoved() {
		return removed;
	}

	public void setRemoved(Boolean removed) {
		this.removed = removed;
	}

	public Integer getIdSensorValue() {
		return idSensorValue;
	}

	public void setIdSensorValue(Integer idSensorValue) {
		this.idSensorValue = idSensorValue;
	}

	public Long getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(Long timestamp) {
		this.timestamp = timestamp;
	}

	public Integer getBoxNumber() {
		return boxNumber;
	}

	public void setBoxNumber(Integer boxNumber) {
		this.boxNumber = boxNumber;
	}

	@Override
	public String toString() {
		return "SensorValue [idSensorValue=" + idSensorValue + ", value=" + value + ", idSensor=" + idSensor
				+ ", timestamp=" + timestamp + ", removed=" + removed + ", boxNumber=" + boxNumber + "]";
	}

	@Override
	public int hashCode() {
		return Objects.hash(boxNumber, idSensor, idSensorValue, removed, timestamp, value);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SensorValue other = (SensorValue) obj;
		return Objects.equals(boxNumber, other.boxNumber) && Objects.equals(idSensor, other.idSensor)
				&& Objects.equals(idSensorValue, other.idSensorValue) && Objects.equals(removed, other.removed)
				&& Objects.equals(timestamp, other.timestamp) && Objects.equals(value, other.value);
	}

	public boolean equalsWithNoIdConsidered(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SensorValue other = (SensorValue) obj;
		if (idSensor == null) {
			if (other.idSensor != null)
				return false;
		} else if (!idSensor.equals(other.idSensor))
			return false;
		if (removed == null) {
			if (other.removed != null)
				return false;
		} else if (!removed.equals(other.removed))
			return false;
		if (timestamp == null) {
			if (other.timestamp != null)
				return false;
		} else if (!timestamp.equals(other.timestamp))
			return false;
		if (value == null) {
			if (other.value != null)
				return false;
		} else if (!value.equals(other.value))
			return false;
		if (boxNumber == null) {
			if (other.boxNumber != null)
				return false;
		} else if (!boxNumber.equals(other.boxNumber))
			return false;
		return true;
	}

}
